name: myqlm2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.4
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nb_conda_kernels=2.3.1
  - ncurses=6.3
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.13.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.4
  - python=3.9.11
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyzmq=22.3.0
  - readline=8.1.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.38.2
  - stack_data=0.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - pip:
    - beautifulsoup4==4.10.0
    - bitstring==3.1.9
    - cryptography==36.0.2
    - cvxpy==1.2.0
    - cycler==0.11.0
    - debugpy==1.6.0
    - dill==0.3.4
    - ecos==2.0.10
    - entrypoints==0.4
    - fastjsonschema==2.15.3
    - fonttools==4.31.2
    - ipykernel==6.12.1
    - ipywidgets==7.7.0
    - jinja2==3.1.1
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.2.1
    - jupyter-console==6.4.3
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.2
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - myqlm==1.5.1
    - myqlm-simulators==1.5.1
    - nbclient==0.5.13
    - nbconvert==6.4.5
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - networkx==2.7.1
    - notebook==6.4.10
    - osqp==0.6.2.post5
    - pillow==9.1.0
    - ply==3.11
    - prettytable==3.2.0
    - prompt-toolkit==3.0.29
    - psutil==5.9.0
    - pydoe==0.3.8
    - pyopenssl==22.0.0
    - pyrsistent==0.18.1
    - qat-comm==1.3.4
    - qat-core==1.5.1
    - qat-devices==0.1.5
    - qat-hardware==1.2.3
    - qat-lang==2.1.3
    - qat-quops==1.2.1
    - qat-variational==1.3.3
    - qdldl==0.1.5.post2
    - qlmaas==1.4.1
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - qutip==4.6.3
    - scipy==1.8.0
    - scs==3.2.0
    - soupsieve==2.3.1
    - svgwrite==1.4.2
    - terminado==0.13.3
    - testpath==0.6.0
    - thrift==0.13.0
    - wand==0.6.7
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
